config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get root                        to: 'home#index'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    get 'categories/:id',           to: 'taxons#show', as: 'category'
    get '/cart',                    to: 'orders#edit', as: :cart
    patch '/cart',                  to: 'orders#update', as: :update_cart
    post '/orders/populate',        to: 'orders#populate'
    resources :products,            only: [:show, :index] do
      get :search, on: :collection
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_type_decorator.rb
Spree::OptionType.class_eval do
  scope :option_values, ->(option_type) { find_by(name: option_type).option_values }
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :category_products, ->(taxon) { joins(:taxons).where(spree_taxons: { id: taxon.self_and_descendants.ids }) }
  scope :related_products, ->(product) { joins(:taxons).where(spree_taxons: { id: product.taxons.ids }).except_self(product).distinct }
  scope :except_self, ->(product) { where.not(id: product.id) }
  scope :within_2weeks, -> { where(available_on: 2.weeks.ago..Time.zone.now) }
  scope :within_3months, -> { where(available_on: 3.months.ago..Time.zone.now) }

  class << self
    def new_arrival
      num = 20
      within_2weeks.count >= num ? within_2weeks.sample(num) : within_3months.order(available_on: :desc).first(num)
    end

    def sorted_by(sort_type = "新着順")
      case sort_type
      when "新着順"
        order(available_on: :desc)
      when "安い順"
        ascend_by_master_price
      when "高い順"
        descend_by_master_price
      when "古い順"
        order(available_on: :asc)
      else
        order(available_on: :desc)
      end
    end

    def ransackable_attributes(_auth_object = nil)
      %w(name description)
    end
  end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  class << self
    def root_categories
      taxonomies = Spree::Taxonomy.all
      where(taxonomy_id: taxonomies.ids, parent_id: nil)
    end
  end
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  class << self
    def sorted_by(sort_type = "新着順")
      case sort_type
      when "新着順"
        joins(:product).order("spree_products.available_on desc")
      when "安い順"
        joins(product: { master: :default_price }).order("spree_prices.amount asc")
      when "高い順"
        joins(product: { master: :default_price }).order("spree_prices.amount desc")
      when "古い順"
        joins(:product).order("spree_products.available_on asc")
      else
        joins(:product).order("spree_products.available_on desc")
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/has_cart_context.rb
module HasCartContext
  extend ActiveSupport::Concern
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def set_order
    @order = current_order || Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
  end
end

app/controllers/concerns/param_option.rb
module ParamOption
  def param_option
    @display_type = params[:display_type] || 'grid'
    @sort_option = %w(新着順 安い順 高い順 古い順)
  end
end

app/controllers/concerns/sidebar_list.rb
module SidebarList
  def sidebar_list
    @root_categories = Spree::Taxon.root_categories
    @color_list = Spree::OptionType.option_values('tshirt-color')
    @size_list = Spree::OptionType.option_values('tshirt-size')
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  include HasCartContext
  before_action :set_order, only: :index

  def index
    @q = Spree::Product.ransack(params[:q])
    @new_arrival_products = Spree::Product.new_arrival
    popular_category_list = ["T-Shirts", "Bags", "Mugs"]
    @popular_categories = Spree::Taxon.where(name: popular_category_list)
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include HasCartContext
  before_action :assign_order, only: :update
  before_action :set_order, only: :edit

  def edit
    @q = Spree::Product.ransack(params[:q])
  end

  def update
    @order.contents.update_cart(order_params)
    redirect_to potepan_cart_path
  end

  def populate
    @order   = current_order(create_order_if_necessary: true)
    variant  = Spree::Variant.find(params[:variant_id] || params[:order][:variant_id])
    quantity = params[:quantity].present? ? params[:quantity].to_i : 1
    @line_item = @order.contents.add(variant, quantity)
    redirect_to potepan_cart_path
  end

  private

  def order_params
    if params[:order]
      params[:order].permit(line_items_attributes: [:id, :quantity])
    else
      {}
    end
  end

  def assign_order
    @order = current_order
    unless @order
      flash[:error] = t('spree.order_not_found')
      redirect_to(potepan_root_path) && return
    end
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  include ParamOption
  include SidebarList
  include HasCartContext
  before_action :set_order, only: [:show, :index, :search]

  def show
    @q = Spree::Product.ransack(params[:q])
    @product = Spree::Variant.find(params[:id])
    @product_properties = @product.product.product_properties.includes(:property)
    @related_products = Spree::Product.related_products(@product.product).sample(4)
  end

  def index
    set_action
  end

  def search
    set_action
    render :index
  end

  private

  def products
    if params[:option_name].present?
      @products = @option_value.variants.sorted_by(params[:sort])
    elsif params[:q]
      @products = @q.result.sorted_by(params[:sort])
    else
      @products = Spree::Product.all.sorted_by(params[:sort])
    end
  end

  def set_action
    @option_value = Spree::OptionValue.find_by(name: params[:option_name])
    @q = Spree::Product.ransack(params[:q])
    sidebar_list
    param_option
    products
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/taxons_controller.rb
class Potepan::TaxonsController < ApplicationController
  include ParamOption
  include SidebarList
  include HasCartContext
  before_action :set_order, only: :show

  def show
    @q = Spree::Product.ransack(params[:q])
    param_option
    sidebar_list
    @category = Spree::Taxon.find(params[:id])
    @category_products = Spree::Product.category_products(@category)
    @products = @category_products.sorted_by(params[:sort])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Potepanec'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/views/layouts/_copy_right.html.erb
<!-- COPY RIGHT -->
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016 Copyright Bigbag Store Bootstrap Template by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
          <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
          <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<div class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>BRANDS</h5>
          <ul class="list-unstyled">
            <li><a href="#">Barbour </a></li>
            <li><a href="#">Brioni </a></li>
            <li><a href="#">Oliver Spencer</a></li>
            <li><a href="#">Belstaff</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Get in Touch</h5>
          <ul class="list-unstyled">
            <li>Call us at (555)-555-5555</li>
            <li><a href="mailto:support@iamabdus.com">support@iamabdus.com</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="newsletter clearfix">
          <h4>Newsletter</h4>
          <h3>Sign up now</h3>
          <p>Enter your email address and get notified about new products. We hate spam!</p>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
            <a href="#" class="input-group-addon" id="basic-addon2">go <i class="glyphicon glyphicon-chevron-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'layouts/copy_right' %>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <%= render 'layouts/topbar' %>
  <%= render 'layouts/navbar' %>
</div>

app/views/layouts/_login_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="">Enter Email</label>
            <input type="text" class="form-control" id="">
          </div>
          <div class="form-group">
            <label for="">Password</label>
            <input type="password" class="form-control" id="">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_meta_tag.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/layouts/_modal.html.erb
<%= render 'layouts/login_modal' %>
<%= render 'layouts/signup_modal' %>
<%= render 'layouts/product_quick_view_modal' %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all' %>

app/views/layouts/_topbar.html.erb
<!-- TOPBAR -->
<div class="topBar">
  <div class="container">
    <div class="row">
      <div class="col-md-6 hidden-sm hidden-xs">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
          <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
          <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
        </ul>
      </div>
      <div class="col-md-6 col-xs-12">
        <ul class="list-inline pull-right">
          <li><span><a data-toggle="modal" href='#login'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>Create an account</a></span></li>
          <li class="dropdown searchBox">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li>
                <span class="input-group">
                  <%= search_form_for(@q, url: search_potepan_products_path, html: { method: :get }) do |f| %>
                    <%= f.search_field :name_or_description_cont, class: "form-control", placeholder: "Search…", "aria-describedby": "basic-addon2"  %>
                    <%= f.submit "Search", class: "input-group-addon", id: "basic-addon2" %>
                  <% end %>
                </span>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i><%= @order.display_total.to_html %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><%= @order.line_items.size %> Item(s) in your cart</li>
                <% @order.line_items.each do |line_item| %>
                  <li>
                    <%= link_to potepan_product_path(line_item.variant_id) do %>
                      <div class="media">
                        <%= image_tag(line_item.variant.images.first.attachment.url(:mini), class: "media-left media-object", alt: "cart-Image") %>
                        <div class="media-body">
                          <h5 class="media-heading"><%= truncate(line_item.name, length: 20) %> <br><span><%= "#{line_item.quantity} X #{line_item.display_amount.to_html}" %></span></h5>
                        </div>
                      </div>
                    <% end %>
                  </li>
                <% end %>
              <li>
                <div class="btn-group" role="group" aria-label="...">
                  <button type="button" class="btn btn-default"><%= link_to "Shopping Cart", potepan_cart_path, id: "shopping-cart-button" %></button>
                  <button type="button" class="btn btn-default">Checkout</button>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/potepan/home/_new_arrival_products.html.erb
<% if new_arrival_products.present? %>
<div class="row featuredProducts">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>新着商品</h4>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="owl-carousel featuredProductsSlider">
      <% new_arrival_products.each do |product| %>
        <div class="slide">
          <div class="productImage clearfix">
            <%= image_tag(product.images.first.attachment.url, :alt => "featured-product-img") %>
            <div class="productMasking">
              <ul class="list-inline btn-group" role="group">
                <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="productCaption clearfix">
            <a href="single_product.html">
              <h5><%= link_to product.name, potepan_product_path(product.id) %></h5>
            </a>
            <h3><%= product.display_price %></h3>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/potepan/home/_popular_category.html.erb
<div class="row featuredCollection">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>人気カテゴリー</h4>
    </div>
  </div>
  <% @popular_categories.each do |category| %>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='<%= potepan_category_path(category.id) %>';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-#{category.name}.jpg", :alt => "feature-collection-image") %>
        <div class="masking"><%= link_to "View #{category.name}", potepan_category_path(category.id), class: "btn viewBtn" %></div>
      </div>
      <div class="caption">
        <h4><%= category.name %></h4>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/potepan/orders/_form.html.erb
<%= form_for order, url: potepan_update_cart_path, html: {id: 'update-cart'} do |order_form| %>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>商品名</th>
          <th>価格</th>
          <th>数</th>
          <th>小計</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "line_item", collection: order.line_items, locals: { order_form: order_form } %>
      </tbody>
    </table>
  </div>
  <div class="updateArea">
   <!--  <div class="input-group">
      <input type="text" class="form-control" placeholder="I have a discount coupon" aria-describedby="basic-addon2">
      <a href="#" class="btn input-group-addon" id="basic-addon2">apply coupon</a>
    </div> -->
    <%= order_form.submit "アップデート", class: "btn" %>
  </div>
  <div class="totalAmountArea">
    <div class="col-sm-4 col-sm-offset-8 col-xs-12">
      <ul class="list-unstyled">
        <li>小計 <span><%= order.display_item_total.to_html %></span></li>
        <li>消費税 <span><%= order.display_tax_total.to_html %></span></li>
        <li>総計 <span class="grandTotal"><%= order.display_total.to_html %></span></li>
      </ul>
    </div>
  </div>
  <div class="checkBtnArea">
    <a href="checkout_step_1.html" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
  </div>
<% end %>

app/views/potepan/orders/_line_item.html.erb
<%= order_form.fields_for :line_items, line_item do |item_form| %>
  <tr>
    <td class="col-xs-2">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true", class="delete">&times;</span></button>
      <span class="cartImage">
        <%= link_to potepan_product_path(line_item.variant_id) do %>
          <%= image_tag(line_item.variant.images.first.attachment.url(:small), :alt => "image") %>
        <% end %>
      </span>
    </td>
    <td class="col-xs-4"><%= link_to line_item.name, potepan_product_path(line_item.variant_id), class: "line-item-name" %></td>
    <td class="col-xs-2"><%= line_item.single_money.to_html %></td>
    <td class="col-xs-2"><%= item_form.number_field :quantity, min: 0, class:"line_item_quantity" %></td>
    <td class="col-xs-2"><%= line_item.display_amount.to_html %></td>
  </tr>
<% end %>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.each do |product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="productBox">
        <div class="productImage clearfix">
          <%= image_tag(product.images.first.attachment.url, :alt => "products-img") %>
          <div class="productMasking">
            <ul class="list-inline btn-group" role="group">
              <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
              <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
              <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
            </ul>
          </div>
        </div>
        <div class="productCaption clearfix">
         <h5><%= link_to product.name, potepan_product_path(product.id) %></h5>
         <h3><%= product.display_price %></h3>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/products/index.html.erb
<% params[:option_name].present? ? provide(:title, @option_value.name) : provide(:title, "Products") %>
<%= render 'potepan/shared/products' %>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>

<!-- LIGHT SECTION -->
<%= render 'potepan/shared/light_section_top', object: @product %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <%= render "image", product: @product %>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <% if request.referrer.blank? || request.referrer&.match(/.*products\/\d/) %>
                  <%= link_to potepan_products_path do %>
                    <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                  <% end %>
                <% else %>
                  <%= link_to :back do %>
                    <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                  <% end %>
                <% end %>
              </li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <%= form_for @order, url: potepan_orders_populate_path, method: :post do |f| %>
              <%= render "option_and_quantity_select_tag", product: @product, f: f %>
              <div class="btn-area">
                <%= button_tag type: "submit", class: "btn btn-primary btn-block" do %>
                  カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
                <% end %>
              </div>
            <% end %>
            <%= render "detail", product_properties: @product_properties %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'related_products', related_products: @related_products %>
  </div>
</section>

app/views/potepan/shared/_display_button_categories.html.erb
<%= link_to potepan_category_url(id: @category.id, display_type: "grid", option_name: params[:option_name], sort: params[:sort]), class: grid_button_class do %>
  <i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
<% end %>
<%= link_to potepan_category_url(id: @category.id, display_type: "list", option_name: params[:option_name], sort: params[:sort]), class: list_button_class do %>
  <i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
<% end %>

app/views/potepan/shared/_filter_by_category.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% root_categories.each do |category| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#<%= category.name %>"><%= category.name %><i class="fa fa-plus"></i></a>
            <ul id="<%= category.name %>" class="collapse collapseItem">
              <% category.leaves.each do |leaf| %>
                <li>
                  <%= link_to potepan_category_path(leaf.id) do %>
                    <i class="fa fa-caret-right" aria-hidden="true"></i><%= leaf.name %>
                    <span>(<%= leaf.products.count %>)</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/shared/_filter_by_color.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% color_list.each do |color| %>
        <li>
          <%= link_to potepan_products_url(option_name: "#{color.name}") do %>
          <%= color.name %><span><%= "(#{color.variants.count})" %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/shared/_filter_by_size.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <% size_list.each do |size| %>
        <li>
          <%= link_to potepan_products_url(option_name: "#{size.name}") do %>
            <%= size.name %><span><%= "(#{size.variants.count})" %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/shared/_product_grid.html.erb
<div class="row">
  <% products.each do |product| %>
    <div class="col-sm-4 col-xs-12">
      <div class="productBox">
        <div class="productImage clearfix">
          <%= image_tag(product.images.first.attachment.url, :alt => "products-img") %>
          <div class="productMasking">
            <ul class="list-inline btn-group" role="group">
              <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
              <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
              <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
            </ul>
          </div>
        </div>
        <div class="productCaption clearfix">
          <h5><%= link_to product.name, potepan_product_path(product.id) %></h5>
          <h3><%= product.display_price %></h3>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/shared/_product_list.html.erb
<div class="row productListSingle">
  <% products.each do |product| %>
    <div class="col-xs-12">
      <div class="media">
        <div class="media-left">
          <%= image_tag(product.images.first.attachment.url, :class => "media-object", :alt => "Image") %>
          <span class="maskingImage"><a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><a href="single-product.html"><%= link_to product.name, potepan_product_path(product.id) %></a></h4>
          <p><%= product.description %></p>
          <h3><%= product.display_price %></h3>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
            <button type="button" class="btn btn-default" onclick="location.href='cart-page.html';"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>